"""Part-type overhang tables and the classification rules over them.

The YTK table is the one implemented kit: Lee, DeLoache, Cervantes & Dueber,
*ACS Synth. Biol.* 2015 (`sb500366v`), Supplementary Figures S6-S18. Every
overhang is the 4-nt **top-strand** overhang generated by BsaI (``GGTCTC(1/5)``),
written 5'->3'.

The eight part positions close into a circle: type 8 ends on ``CCCT``, which is
where type 1 begins. That circle is the whole model. A part is a contiguous arc
of it, named by the positions it spans, and the arc must not cross the 8/1
boundary - which is what tells a real part from the backbone left over when you
cut one out.

Two enzymes, two jobs
---------------------
Which enzyme cuts decides what the plasmid *is*, whatever its file says:

* the **part enzyme** (BsaI here) releases type 1-8 parts and assembles the
  eight of them into one transcription unit;
* the **multigene enzyme** (BsmBI here) makes part entry vectors and joins
  finished cassettes into a multigene construct.

A `Scheme` binds those two enzymes to a table, so a different kit - MoClo with
its own positions, a Loop-style scheme, an enzyme pair chosen to dodge an
internal site - is a new `Scheme`, not a change to the code that uses one.
Everything here takes `scheme` as a keyword argument defaulting to `YTK`.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from .enzymes import BBSI, BSAI, BSMBI, NOTI, Enzyme


@dataclass(frozen=True)
class Scheme:
    """An assembly standard: two enzymes and the overhang circle they run on."""

    name: str
    part_enzyme: Enzyme
    """Releases parts and builds one transcription unit from them."""
    multigene_enzyme: Enzyme
    """Builds part entry vectors, and joins cassettes into a multigene plasmid."""
    linearizer: Enzyme
    """Cuts an integration vector open before transformation."""
    boundaries: tuple[str, ...]
    """Overhangs in order around the circle; the first is repeated at the end."""
    atoms: tuple[str, ...]
    """The indivisible arcs between consecutive boundaries."""
    merges: tuple[tuple[str, str, str], ...] = ()
    """Half-positions that collapse to a whole one: (first, second, whole)."""
    alternate_cloning_enzymes: tuple[Enzyme, ...] = ()
    """Other enzymes a destination vector may use to take an insert, so a part
    carrying an internal site for one of them can still be cloned."""
    entry_vector_overhangs: tuple[str, str] = ()
    """The multigene enzyme's overhangs on the part entry vector."""
    descriptions: dict[str, str] = field(default_factory=dict)
    colors: dict[str, str] = field(default_factory=dict)
    badges: dict[str, tuple[str, str]] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if len(self.boundaries) != len(self.atoms) + 1:
            raise ValueError("a scheme needs one more boundary than it has atoms")
        if self.boundaries[0] != self.boundaries[-1]:
            raise ValueError("the boundary list must close the circle")

    @property
    def reserved_overhangs(self) -> frozenset[str]:
        """Overhangs an internally chosen junction must avoid, and not 3-of-4 match."""
        return frozenset(self.entry_vector_overhangs)

    @property
    def overhang_length(self) -> int:
        return self.part_enzyme.overhang_length


#: The YTK overhang circle. ``CCCT`` appears at both ends: it closes the circle,
#: and listing it twice makes a span a simple forward slice.
YTK_BOUNDARIES: tuple[str, ...] = (
    "CCCT",  # 1
    "AACG",  # 2
    "TATG",  # 3a
    "TTCT",  # 3b
    "ATCC",  # 4a
    "TGGC",  # 4b
    "GCTG",  # 5
    "TACA",  # 6
    "GAGT",  # 7
    "CCGA",  # 8a
    "CAAT",  # 8b
    "CCCT",
)

YTK_ATOMS: tuple[str, ...] = ("1", "2", "3a", "3b", "4a", "4b", "5", "6", "7", "8a", "8b")

YTK_MERGES: tuple[tuple[str, str, str], ...] = (
    ("3a", "3b", "3"),
    ("4a", "4b", "4"),
    ("8a", "8b", "8"),
)

YTK_DESCRIPTIONS: dict[str, str] = {
    "1": "5' assembly connector (ConLX / ConLX')",
    "2": "Promoter (3' overhang is the ATG start codon)",
    "3": "CDS (whole)",
    "3a": "CDS, N-terminal half",
    "3b": "CDS, C-terminal half",
    "4": "Terminator (whole)",
    "4a": "C-terminal CDS fusion",
    "4b": "Terminator",
    "5": "3' assembly connector (ConRX / ConRX')",
    "6": "Yeast selectable marker",
    "7": "Yeast origin, or 3' genomic homology arm",
    "8": "E. coli origin + resistance (whole)",
    "8a": "E. coli origin + resistance",
    "8b": "5' genomic homology arm",
    "234": "Cassette insert (promoter-CDS-terminator)",
    "234r": "GFP dropout, part-enzyme sites reversed - consumed, never released",
    "678": "Marker, yeast origin and E. coli origin+resistance",
}

#: Map colours, one per position, taken from the design canvas
#: (docs/design/level2_cassette.html) and mirrored in web/tokens.css as
#: --part-N. Half-positions share their whole position's hue so a split panel
#: still reads as one arc of the circle.
YTK_COLORS: dict[str, str] = {
    "1": "#6E9FC0",
    "2": "#8FB861",
    "3": "#D9C45A",
    "3a": "#D9C45A",
    "3b": "#C9B24A",
    "4": "#D97F92",
    "4a": "#E09AA8",
    "4b": "#D97F92",
    "5": "#8E73C4",
    "6": "#D9AB5E",
    "7": "#9E6A3C",
    "8": "#8C8A86",
    "8a": "#8C8A86",
    "8b": "#A8A6A2",
}

#: The paler badge pair the panels use for the position number.
YTK_BADGES: dict[str, tuple[str, str]] = {
    "1": ("#DCEAF3", "#1F4F6B"),
    "2": ("#E4F0D5", "#3E5C1E"),
    "3": ("#F5EFCE", "#6B5A12"),
    "4": ("#F8DEE3", "#7A2437"),
    "5": ("#E8E0F5", "#45307A"),
    "6": ("#F7E9CE", "#6E4C13"),
    "7": ("#EFE0D2", "#5C3A18"),
    "8": ("#E6E4E1", "#3A3A38"),
}

#: The standard Yeast Toolkit: BsaI for parts, BsmBI for multigene, NotI to cut open.
YTK = Scheme(
    name="YTK",
    part_enzyme=BSAI,
    multigene_enzyme=BSMBI,
    linearizer=NOTI,
    boundaries=YTK_BOUNDARIES,
    atoms=YTK_ATOMS,
    merges=YTK_MERGES,
    alternate_cloning_enzymes=(BBSI,),
    entry_vector_overhangs=("TCGG", "GACC"),
    descriptions=YTK_DESCRIPTIONS,
    colors=YTK_COLORS,
    badges=YTK_BADGES,
)

SCHEMES: dict[str, Scheme] = {YTK.name.lower(): YTK}

#: Module-level aliases for the default scheme, for readability at call sites.
BOUNDARIES = YTK.boundaries
ATOMS = YTK.atoms
MERGES = YTK.merges
DESCRIPTIONS = YTK.descriptions
ENTRY_VECTOR_OVERHANGS = YTK.entry_vector_overhangs
RESERVED_OVERHANGS = YTK.reserved_overhangs


def get_scheme(name: str) -> Scheme:
    try:
        return SCHEMES[name.lower()]
    except KeyError:
        raise ValueError(f"unknown scheme: {name}") from None


@dataclass(frozen=True)
class SpanCall:
    """The arc of the circle that an overhang pair delimits."""

    name: str
    """Canonical part name, e.g. ``3a``, ``234``, ``1234567``."""
    atoms: tuple[str, ...]
    five_prime: str
    three_prime: str
    legal: bool
    """False when the arc crosses the 8/1 boundary - i.e. it is a backbone."""
    reversed_sites: bool = False
    scheme: str = YTK.name

    @property
    def display_name(self) -> str:
        return f"{self.name}r" if self.reversed_sites else self.name

    @property
    def description(self) -> str:
        table = get_scheme(self.scheme).descriptions
        return table.get(self.display_name, table.get(self.name, "composite part"))

    @property
    def is_full_circle(self) -> bool:
        return len(self.atoms) == len(get_scheme(self.scheme).atoms)


def collapse(atoms: tuple[str, ...] | list[str], scheme: Scheme = YTK) -> str:
    """Name an atom run, merging half-positions back into whole ones."""
    parts: list[str] = []
    atoms = list(atoms)
    i = 0
    while i < len(atoms):
        merged = None
        if i + 1 < len(atoms):
            for first, second, whole in scheme.merges:
                if atoms[i] == first and atoms[i + 1] == second:
                    merged = whole
                    break
        if merged:
            parts.append(merged)
            i += 2
        else:
            parts.append(atoms[i])
            i += 1
    return "".join(parts)


def span(
    five_prime: str,
    three_prime: str,
    reversed_sites: bool = False,
    scheme: Scheme = YTK,
) -> SpanCall | None:
    """Resolve an overhang pair to an arc of the circle.

    Returns None when either overhang is not a boundary of this scheme at all,
    and a `SpanCall` with ``legal=False`` when the pair is a real arc but
    crosses the 8/1 boundary - which is what a cut-out backbone looks like.
    """
    five, three = five_prime.upper(), three_prime.upper()
    boundaries = scheme.boundaries
    if five not in boundaries or three not in boundaries:
        return None

    start = boundaries.index(five)
    end = len(boundaries) - 1 - tuple(reversed(boundaries)).index(three)
    if start >= end:
        return SpanCall("", (), five, three, legal=False,
                        reversed_sites=reversed_sites, scheme=scheme.name)

    atoms = scheme.atoms[start:end]
    return SpanCall(
        name=collapse(atoms, scheme),
        atoms=tuple(atoms),
        five_prime=five,
        three_prime=three,
        legal=True,
        reversed_sites=reversed_sites,
        scheme=scheme.name,
    )


def type_overhangs(name: str, scheme: Scheme = YTK) -> tuple[str, str] | None:
    """The (5', 3') overhang pair for a part-type name, e.g. ``234`` or ``3a``."""
    atoms = expand(name, scheme)
    if not atoms:
        return None
    start = scheme.atoms.index(atoms[0])
    end = scheme.atoms.index(atoms[-1]) + 1
    return scheme.boundaries[start], scheme.boundaries[end]


def expand(name: str, scheme: Scheme = YTK) -> tuple[str, ...]:
    """The atoms a part-type name covers. ``3`` -> ``(3a, 3b)``; ``()`` if bad."""
    name = name.strip().rstrip("r")
    wholes = {whole for _, _, whole in scheme.merges}
    atoms: list[str] = []
    i = 0
    while i < len(name):
        token = name[i]
        if i + 1 < len(name) and name[i + 1] in "ab":
            token += name[i + 1]
            i += 2
        else:
            i += 1
        if token in scheme.atoms:
            atoms.append(token)
        elif token in wholes:
            first, second = next((f, s) for f, s, w in scheme.merges if w == token)
            atoms.extend([first, second])
        else:
            return ()
    if not atoms:
        return ()
    indices = [scheme.atoms.index(a) for a in atoms]
    if indices != list(range(indices[0], indices[0] + len(indices))):
        return ()
    return tuple(atoms)


def positions(name: str, scheme: Scheme = YTK) -> list[str]:
    """The whole positions a part-type name covers: ``234`` -> [2, 3, 4]."""
    atoms = expand(name, scheme)
    out: list[str] = []
    for atom in atoms:
        position = atom[0]
        if position not in out:
            out.append(position)
    return out


def is_composite(name: str | None, scheme: Scheme = YTK) -> bool:
    """True for a part spanning more than one position, e.g. ``234`` or ``678``.

    A whole type 3 is not composite: it spans one position, in two halves.
    """
    return bool(name) and len(positions(name, scheme)) > 1


def is_known_type(name: str, scheme: Scheme = YTK) -> bool:
    return bool(expand(name, scheme))


def color_for(part_type: str | None, scheme: Scheme = YTK) -> str:
    """A map colour for a part type, falling back to the first position it spans."""
    if not part_type:
        return "#B0B0B0"
    base = part_type.rstrip("r")
    if base in scheme.colors:
        return scheme.colors[base]
    atoms = expand(base, scheme)
    return scheme.colors.get(atoms[0], "#B0B0B0") if atoms else "#B0B0B0"


def badge_for(part_type: str | None, scheme: Scheme = YTK) -> tuple[str, str]:
    """The (background, foreground) pair a panel badge uses for a part type."""
    if not part_type:
        return ("#E6E4E1", "#3A3A38")
    base = part_type.rstrip("r")
    badges = YTK_BADGES if scheme is YTK else {}
    if base in badges:
        return badges[base]
    atoms = expand(base, scheme)
    position = atoms[0][0] if atoms else ""
    return badges.get(position, ("#E6E4E1", "#3A3A38"))


def near_match(a: str, b: str) -> bool:
    """True when two overhangs are equal or differ at a single position."""
    a, b = a.upper(), b.upper()
    if a == b:
        return True
    if len(a) != len(b):
        return False
    return sum(1 for x, y in zip(a, b, strict=True) if x != y) == 1


def conflicts_with_reserved(overhang: str, scheme: Scheme = YTK) -> str | None:
    """The reserved overhang a chosen junction collides with, if any.

    A junction the app picks itself must avoid the entry vector's overhangs and
    must not 3-of-4 match them.
    """
    for reserved in sorted(scheme.reserved_overhangs):
        if near_match(overhang, reserved):
            return reserved
    return None
